#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

set -e

# Ensure that the project compiles, also prepare it for the check
npm run build

npm run --silent check-commands

# Format files
npx pretty-quick --staged
