#! /bin/bash
. "$(dirname "$0")/_/husky.sh"

set -e

# Ensure that the project compiles, also prepare it for the check

if [ -z "${DIRTY+1}" ]; then
    npm run build || exit
    rm -f DIRTY.md
    git rm --cached DIRTY.md >/dev/null 2>&1 || true
    npm run --silent check-commands
    # Lint and format files
else
    # indentation matters until after EOF
    cat << EOF > DIRTY.md
# WARNING
Beware! This commit will _not_ work; it may not even compile correctly.
EOF
    git add DIRTY.md
fi

npx lint-staged
