#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

set -e

# Ensure that the project compiles, also prepare it for the check

if [ ! -e .dirty ]; then
    npm run build
fi

npm run --silent check-commands

# Format files
npx pretty-quick --staged
